### ISSUE TITLE
Tower Hero update to 2.10

### ISSUE THREAD

**Issue by dgjungleP** [pie3636/pie3636.github.io#6]
Hi @pie3636, Tower Hero is updated to 2.10. It adds some new equipment. Would you like to upgrade your tool?
It's beneficial for me.
Thanks.

**Comment by pie3636** [comment]
Hello,
Sorry for replying so late, but it has been very difficult for me to understand Tatsuki's code after 2.0.0. I should be able to update the simulator in a few days.

**Comment by dgjungleP** [comment]
> Hello, Sorry for replying so late, but it has been very difficult for me to understand Tatsuki's code after 2.0.0. I should be able to update the simulator in a few days.

I'm so glad to get your reply. Could I do something about this? Even if I don't do any work for Tatsuki's code, I want to have a try.

**Comment by pie3636** [comment]
Hello,
This should be fixed as of now. The update for the latest version (adding soldier skills and Flash Orb) should also be up in a few days or weeks once I obtain the source code.
